#!/usr/bin/env python3

import sys
from scripts import *
import subprocess
import os
#sync test folder with vcs folder and run inside test folder
subprocess.run(["./sync_test_folder"], cwd='/home/vishant/Programming/VCS')
os.chdir('/home/vishant/Programming/VCS/test')

base_command = sys.argv[1]
if( base_command == 'init' ) : init()
if( base_command == 'commit' ) : commit()
if( base_command == 'log' ) : log()